name: Deploy to Dreamhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Verify SSH key permissions
      run: |
        ls -lah ~/.ssh/

    - name: SSH Debug Connection
      run: |
        ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no dh_etmf7k@iad1-shared-e1-17.dreamhost.com "echo SSH connection successful"

    - name: Deploy to Dreamhost
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ dh_etmf7k@iad1-shared-e1-17.dreamhost.com:/tylerolmsted.co
