name: Deploy to Dreamhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Dreamhost
      run: |
        rsync -avz --delete ./ dh_etmf7k@iad1-shared-e1-17.dreamhost.com:/tylerolmsted.co