name: Deploy to Dreamhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup SSH Environment for RSA key
    - name: Setup SSH Environment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H iad1-shared-e1-17.dreamhost.com >> ~/.ssh/known_hosts
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    # Debug SSH Connection Directly using RSA key
    - name: SSH Debug Connection
      run: |
        ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no dh_etmf7k@iad1-shared-e1-17.dreamhost.com "echo SSH connection successful"

    - name: Deploy to Dreamhost
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ dh_etmf7k@iad1-shared-e1-17.dreamhost.com:/tylerolmsted.co
